spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_health?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379
    # password: 如果有密码
    database: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.health.domain.pojo

mybatis:
  mapper-locations: classpath:com/health/mapper/*.xml

aliyun: # 新增的配置块
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId:        # 你的 AccessKey ID
    accessKeySecret:  # 替你的 AccessKey Secret
    bucketName:             # 替你的 Bucket 名称
